























.build_ano/uno/Pushbutton/Pushbutton.o : lib/Pushbutton/Pushbutton.cpp
	@echo [93mPushbutton/Pushbutton.cpp[0m
	@mkdir -p .build_ano/uno/Pushbutton
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c lib/Pushbutton/Pushbutton.cpp
include .build_ano/uno/Pushbutton/Pushbutton.d



.build_ano/uno/Pushbutton/libPushbutton.a : .build_ano/uno/Pushbutton/Pushbutton.o
	@echo [92mLinking libPushbutton.a[0m
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build_ano/uno/QTRSensors/QTRSensors.o : lib/QTRSensors/QTRSensors.cpp
	@echo [93mQTRSensors/QTRSensors.cpp[0m
	@mkdir -p .build_ano/uno/QTRSensors
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c lib/QTRSensors/QTRSensors.cpp
include .build_ano/uno/QTRSensors/QTRSensors.d



.build_ano/uno/QTRSensors/libQTRSensors.a : .build_ano/uno/QTRSensors/QTRSensors.o
	@echo [92mLinking libQTRSensors.a[0m
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build_ano/uno/Motion/Motion.o : lib/Motion/Motion.cpp
	@echo [93mMotion/Motion.cpp[0m
	@mkdir -p .build_ano/uno/Motion
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c lib/Motion/Motion.cpp
include .build_ano/uno/Motion/Motion.d

.build_ano/uno/Motion/TurnSensor.o : lib/Motion/TurnSensor.cpp
	@echo [93mMotion/TurnSensor.cpp[0m
	@mkdir -p .build_ano/uno/Motion
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c lib/Motion/TurnSensor.cpp
include .build_ano/uno/Motion/TurnSensor.d

.build_ano/uno/Motion/Utilities.o : lib/Motion/Utilities.cpp
	@echo [93mMotion/Utilities.cpp[0m
	@mkdir -p .build_ano/uno/Motion
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c lib/Motion/Utilities.cpp
include .build_ano/uno/Motion/Utilities.d



.build_ano/uno/Motion/libMotion.a : .build_ano/uno/Motion/Motion.o .build_ano/uno/Motion/TurnSensor.o .build_ano/uno/Motion/Utilities.o
	@echo [92mLinking libMotion.a[0m
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build_ano/uno/L3G/L3G.o : lib/L3G/L3G.cpp
	@echo [93mL3G/L3G.cpp[0m
	@mkdir -p .build_ano/uno/L3G
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c lib/L3G/L3G.cpp
include .build_ano/uno/L3G/L3G.d



.build_ano/uno/L3G/libL3G.a : .build_ano/uno/L3G/L3G.o
	@echo [92mLinking libL3G.a[0m
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^














.build_ano/uno/ZumoReflectanceSensorArray/libZumoReflectanceSensorArray.a : 
	@echo [92mLinking libZumoReflectanceSensorArray.a[0m
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^







.build_ano/uno/Wire/utility/twi.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility/twi.c
	@echo [93mWire/utility/twi.c[0m
	@mkdir -p .build_ano/uno/Wire/utility
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino   -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility/twi.c
include .build_ano/uno/Wire/utility/twi.d






.build_ano/uno/Wire/Wire.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/Wire.cpp
	@echo [93mWire/Wire.cpp[0m
	@mkdir -p .build_ano/uno/Wire
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/Wire.cpp
include .build_ano/uno/Wire/Wire.d



.build_ano/uno/Wire/libWire.a : .build_ano/uno/Wire/utility/twi.o .build_ano/uno/Wire/Wire.o
	@echo [92mLinking libWire.a[0m
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build_ano/uno/ZumoMotors/ZumoMotors.o : lib/ZumoMotors/ZumoMotors.cpp
	@echo [93mZumoMotors/ZumoMotors.cpp[0m
	@mkdir -p .build_ano/uno/ZumoMotors
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c lib/ZumoMotors/ZumoMotors.cpp
include .build_ano/uno/ZumoMotors/ZumoMotors.d



.build_ano/uno/ZumoMotors/libZumoMotors.a : .build_ano/uno/ZumoMotors/ZumoMotors.o
	@echo [92mLinking libZumoMotors.a[0m
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build_ano/uno/NewPing/NewPing.o : /Users/Swapnull/Documents/Arduino/libraries/NewPing/NewPing.cpp
	@echo [93mNewPing/NewPing.cpp[0m
	@mkdir -p .build_ano/uno/NewPing
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /Users/Swapnull/Documents/Arduino/libraries/NewPing/NewPing.cpp
include .build_ano/uno/NewPing/NewPing.d



.build_ano/uno/NewPing/libNewPing.a : .build_ano/uno/NewPing/NewPing.o
	@echo [92mLinking libNewPing.a[0m
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build_ano/uno/SoftwareSerial/SoftwareSerial.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial/SoftwareSerial.cpp
	@echo [93mSoftwareSerial/SoftwareSerial.cpp[0m
	@mkdir -p .build_ano/uno/SoftwareSerial
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial/SoftwareSerial.cpp
include .build_ano/uno/SoftwareSerial/SoftwareSerial.d



.build_ano/uno/SoftwareSerial/libSoftwareSerial.a : .build_ano/uno/SoftwareSerial/SoftwareSerial.o
	@echo [92mLinking libSoftwareSerial.a[0m
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^







.build_ano/uno/arduino/hooks.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.c
	@echo [93marduino/hooks.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino   -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.c
include .build_ano/uno/arduino/hooks.d

.build_ano/uno/arduino/WInterrupts.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.c
	@echo [93marduino/WInterrupts.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino   -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.c
include .build_ano/uno/arduino/WInterrupts.d

.build_ano/uno/arduino/wiring.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.c
	@echo [93marduino/wiring.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino   -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.c
include .build_ano/uno/arduino/wiring.d

.build_ano/uno/arduino/wiring_analog.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.c
	@echo [93marduino/wiring_analog.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino   -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.c
include .build_ano/uno/arduino/wiring_analog.d

.build_ano/uno/arduino/wiring_digital.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.c
	@echo [93marduino/wiring_digital.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino   -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.c
include .build_ano/uno/arduino/wiring_digital.d

.build_ano/uno/arduino/wiring_pulse.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.c
	@echo [93marduino/wiring_pulse.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino   -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.c
include .build_ano/uno/arduino/wiring_pulse.d

.build_ano/uno/arduino/wiring_shift.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.c
	@echo [93marduino/wiring_shift.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino   -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.c
include .build_ano/uno/arduino/wiring_shift.d






.build_ano/uno/arduino/abi.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.cpp
	@echo [93marduino/abi.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.cpp
include .build_ano/uno/arduino/abi.d

.build_ano/uno/arduino/CDC.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.cpp
	@echo [93marduino/CDC.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.cpp
include .build_ano/uno/arduino/CDC.d

.build_ano/uno/arduino/HardwareSerial.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp
	@echo [93marduino/HardwareSerial.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp
include .build_ano/uno/arduino/HardwareSerial.d

.build_ano/uno/arduino/HardwareSerial0.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp
	@echo [93marduino/HardwareSerial0.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp
include .build_ano/uno/arduino/HardwareSerial0.d

.build_ano/uno/arduino/HardwareSerial1.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp
	@echo [93marduino/HardwareSerial1.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp
include .build_ano/uno/arduino/HardwareSerial1.d

.build_ano/uno/arduino/HardwareSerial2.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp
	@echo [93marduino/HardwareSerial2.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp
include .build_ano/uno/arduino/HardwareSerial2.d

.build_ano/uno/arduino/HardwareSerial3.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp
	@echo [93marduino/HardwareSerial3.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp
include .build_ano/uno/arduino/HardwareSerial3.d

.build_ano/uno/arduino/HID.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HID.cpp
	@echo [93marduino/HID.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HID.cpp
include .build_ano/uno/arduino/HID.d

.build_ano/uno/arduino/IPAddress.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.cpp
	@echo [93marduino/IPAddress.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.cpp
include .build_ano/uno/arduino/IPAddress.d

.build_ano/uno/arduino/main.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.cpp
	@echo [93marduino/main.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.cpp
include .build_ano/uno/arduino/main.d

.build_ano/uno/arduino/new.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.cpp
	@echo [93marduino/new.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.cpp
include .build_ano/uno/arduino/new.d

.build_ano/uno/arduino/Print.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.cpp
	@echo [93marduino/Print.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.cpp
include .build_ano/uno/arduino/Print.d

.build_ano/uno/arduino/Stream.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.cpp
	@echo [93marduino/Stream.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.cpp
include .build_ano/uno/arduino/Stream.d

.build_ano/uno/arduino/Tone.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.cpp
	@echo [93marduino/Tone.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.cpp
include .build_ano/uno/arduino/Tone.d

.build_ano/uno/arduino/USBCore.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.cpp
	@echo [93marduino/USBCore.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.cpp
include .build_ano/uno/arduino/USBCore.d

.build_ano/uno/arduino/WMath.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.cpp
	@echo [93marduino/WMath.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.cpp
include .build_ano/uno/arduino/WMath.d

.build_ano/uno/arduino/WString.o : /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.cpp
	@echo [93marduino/WString.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.cpp
include .build_ano/uno/arduino/WString.d



.build_ano/uno/arduino/libarduino.a : .build_ano/uno/arduino/hooks.o .build_ano/uno/arduino/WInterrupts.o .build_ano/uno/arduino/wiring.o .build_ano/uno/arduino/wiring_analog.o .build_ano/uno/arduino/wiring_digital.o .build_ano/uno/arduino/wiring_pulse.o .build_ano/uno/arduino/wiring_shift.o .build_ano/uno/arduino/abi.o .build_ano/uno/arduino/CDC.o .build_ano/uno/arduino/HardwareSerial.o .build_ano/uno/arduino/HardwareSerial0.o .build_ano/uno/arduino/HardwareSerial1.o .build_ano/uno/arduino/HardwareSerial2.o .build_ano/uno/arduino/HardwareSerial3.o .build_ano/uno/arduino/HID.o .build_ano/uno/arduino/IPAddress.o .build_ano/uno/arduino/main.o .build_ano/uno/arduino/new.o .build_ano/uno/arduino/Print.o .build_ano/uno/arduino/Stream.o .build_ano/uno/arduino/Tone.o .build_ano/uno/arduino/USBCore.o .build_ano/uno/arduino/WMath.o .build_ano/uno/arduino/WString.o
	@echo [92mLinking libarduino.a[0m
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^















.build_ano/uno/src/sketch.o : .build_ano/uno/src/sketch.cpp
	@echo [93msrc/sketch.cpp[0m
	@mkdir -p .build_ano/uno/src
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard -Ilib/Pushbutton -Ilib/QTRSensors -Ilib/Motion -Ilib/L3G -Ilib/ZumoReflectanceSensorArray -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/utility -Ilib/ZumoMotors -I/Users/Swapnull/Documents/Arduino/libraries/NewPing -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SoftwareSerial -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -fno-exceptions -iquote src  -o $@ -c .build_ano/uno/src/sketch.cpp
include .build_ano/uno/src/sketch.d







.build_ano/uno/firmware.elf : .build_ano/uno/src/sketch.o .build_ano/uno/Pushbutton/libPushbutton.a .build_ano/uno/QTRSensors/libQTRSensors.a .build_ano/uno/Motion/libMotion.a .build_ano/uno/L3G/libL3G.a .build_ano/uno/ZumoReflectanceSensorArray/libZumoReflectanceSensorArray.a .build_ano/uno/Wire/libWire.a .build_ano/uno/ZumoMotors/libZumoMotors.a .build_ano/uno/NewPing/libNewPing.a .build_ano/uno/SoftwareSerial/libSoftwareSerial.a .build_ano/uno/arduino/libarduino.a
	@echo [92mLinking firmware.elf[0m
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build_ano/uno/firmware.hex : .build_ano/uno/firmware.elf
	@echo [92mConverting to firmware.hex[0m
	@/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build_ano/uno/src/dependencies.d .build_ano/uno/Wire/dependencies.d .build_ano/uno/L3G/dependencies.d .build_ano/uno/Pushbutton/dependencies.d .build_ano/uno/ZumoReflectanceSensorArray/dependencies.d .build_ano/uno/arduino/dependencies.d .build_ano/uno/QTRSensors/dependencies.d .build_ano/uno/Motion/dependencies.d .build_ano/uno/ZumoMotors/dependencies.d .build_ano/uno/NewPing/dependencies.d .build_ano/uno/SoftwareSerial/dependencies.d

all : .build_ano/uno/firmware.hex
	@true

